name: codemelted_web
description: TBD
version: 0.0.0
homepage: https://developer.codemelted.com/codemelted_web/docs
repository: https://github.com/CodeMelted/codemelted_web
# publish_to: none

topics:
  - async
  - audio
  - bluetooth
  - console
  - database
  - dialogs
  - disk
  - fetch
  - file
  - http
  - isolate
  - json
  - layouts
  - link opening
  - logger
  - math
  - process
  - runtime
  - serial
  - sensor
  - sockets
  - storage
  - tcp
  - udp
  - websockets
  - widgets
  - workers

platforms:
  web:

funding:
 - https://www.buymeacoffee.com/codemelted

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # audioplayers: ^5.0.0
  # flutter_tts: ^3.7.0
  # http: ^1.1.0
  # io: ^1.0.4
  logging: ^1.1.1
  # share_plus: ^7.0.2
  # shared_preferences: ^2.0.18
  # url_launcher: ^6.1.10
  # webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
