name: codemelted_web
description: CodeMelted Web Module - Leveraging the power of Flutter and the Web APIs to develop powerful Progressive Web Applications.
version: 0.2.0
homepage: https://developer.codemelted.com/codemelted_web/docs
repository: https://github.com/CodeMelted/codemelted_web
# publish_to: none

topics:
  - logger
  - error

platforms:
  web:

funding:
 - https://www.buymeacoffee.com/codemelted

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  logging: ^1.2.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
